name: Actions Runner Controller With Redis and k8s
on:
  workflow_dispatch:

jobs:
  arc-runner-job:
    runs-on: arc_runner_set_gitk8s
    container: busybox
    steps:
      - name: Trials
        run: |
          echo "Hello World" >> $GITHUB_STEP_SUMMARY
          sleep 180
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
